blog/urls.py
from django.urls import path
from blog import views as blog_views

app_name = 'blog'

urlpatterns = [
    path('post/<int:post_id>/', blog_views.post, name='post'),
    path('example/', blog_views.example, name='example'),
    path('', blog_views.blog, name='home'),
]

home/urls.py
from django.urls import path
from home import views as home_views

app_name = 'home'

urlpatterns = [
    path('', home_views.index, name='home'),
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from blog import views as blog_views

# def home(request):
#     return HttpResponse('This is the home page')

# def my_view(request):
#     return HttpResponse('This tab has succefully opened!')

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpRequest, Http404
from blog.data import posts
from typing import Any

def blog(request):

    context =  {'text': 'On initial blog page',
                'title': 'Blog - ',
                'posts': posts,
                }

    return render(request,
                  'blog/home.html',  context,
    )

def example(request):

    context =  {'text': 'On blog example',
                'title': 'Blog Example - '}

    return render(request,
                  'blog/example.html', context,
    )

def post(request: HttpRequest, post_id: int): 
    found_post:dict[str, Any] | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post == None:
       raise Http404('Not founded')
        

    context =  {'text': 'On initial blog page',
                'title': found_post['title'] + ' - ',
                'post': found_post,
                }

    return render(request,
                  'blog/post.html',  context,
    )


    

home/views.py
from django.shortcuts import render


def index(request):

    context =  {'text': 'On home page',
                'title': 'Home - '}

    return render(
        request, 'home/home.html',
        context,
)

blog/templates/blog/404error.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ERROR</title>
</head>
<body>
    <img src="{% static "img/8030430_3828535.svg" %}" alt="">
</body>
</html>

blog/templates/blog/example.html
{% extends "global/base.html" %}

{% block texto %} {{ text }} {% endblock texto %}

blog/templates/blog/home.html
{% extends "global/base.html" %}

{% if text %}
    {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/base.html" %}

{% if text %}
    {% block texto %} {{ text }} {% endblock texto %}
{% endif %}

{% block posts %}
<article class="post single-post">
    <header>
        <h1 class="post__title">
            <a href="{% url "blog:post" post.id %}">
                {{ post.title }}
            </a>
        </h1>
    </header>
    <div>
        <p class="post__body">
            {{ post.body }}
        </p>
    </div>
</article>
{% endblock posts %}

home/templates/home/home.html
{% extends "global/base.html" %}

{% block texto %} {{ text }} {% endblock texto %}